"use client";

import { useMemo, useState } from "react";
import { AudioLines, Check, ChevronRight, Download, FileAudio, Languages, LoaderCircle, RotateCcw, ShieldCheck, Sparkles, Volume2 } from "lucide-react";

const SAMPLE_ENGLISH = "Data security includes various techniques to prevent unauthorized access and ensure the safety of stored and transmitted data.";
const SAMPLE_GERMAN = "Datensicherheit umfasst verschiedene Techniken zur Verhinderung unbefugten Zugriffs und zur Gewährleistung der Sicherheit gespeicherter und übertragener Daten.";
type Stage = "script" | "voice" | "qc";
type HumanReview = { humanScore:number; verdict:string; pronunciation:string; tone:string; pacing:string; audioQuality:string; humanLikeness:string; summary:string; suggestions:string[] };
type QcResult = { score:number; status:"pass"|"warning"|"fail"; transcript:string; checks:{label:string;detail:string;passed:boolean}[]; humanReview?:HumanReview };
const directionPresets = ["Professional", "Warm", "Authoritative", "Calm", "Flat"];
const voiceOptions = ["marin", "cedar", "coral", "nova"];

export default function Home() {
  const [english,setEnglish]=useState(SAMPLE_ENGLISH); const [german,setGerman]=useState(SAMPLE_GERMAN);
  const [stage,setStage]=useState<Stage>("script"); const [voice,setVoice]=useState("marin"); const [tone,setTone]=useState("Professional");
  const [speed,setSpeed]=useState(50); const [energy,setEnergy]=useState(42);
  const [direction,setDirection]=useState("Clear Standard German. Professional training-video delivery. Precise pronunciation with short, natural pauses.");
  const [audioUrl,setAudioUrl]=useState(""); const [qc,setQc]=useState<QcResult|null>(null); const [busy,setBusy]=useState<"translate"|"generate"|null>(null); const [error,setError]=useState("");
  const words=useMemo(()=>german.trim().split(/\s+/).filter(Boolean).length,[german]);

  async function translate(){setBusy("translate");setError("");try{const response=await fetch("/api/voiceover",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"translate",english})});const data=await response.json();if(!response.ok)throw new Error(data.error||"Translation failed");setGerman(data.translation);setStage("voice");setQc(null);setAudioUrl("")}catch(err){setError(err instanceof Error?err.message:"Translation failed")}finally{setBusy(null)}}
  async function generate(){setBusy("generate");setError("");setQc(null);setAudioUrl("");try{const response=await fetch("/api/voiceover",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"generate",english,german,voice,tone,speed,energy,direction})});const data=await response.json();if(!response.ok)throw new Error(data.error||"Audio generation failed");setAudioUrl(`data:audio/mpeg;base64,${data.audio}`);setQc(data.qc);setStage("qc")}catch(err){setError(err instanceof Error?err.message:"Audio generation failed")}finally{setBusy(null)}}

  return <main className="min-h-screen bg-[#07110e] text-[#eef8f3]">
    <header className="border-b border-white/10 bg-[#091713]/90 px-5 py-4 backdrop-blur md:px-8"><div className="mx-auto flex max-w-[1440px] items-center justify-between"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#80f0bd] text-[#07110e]"><AudioLines size={22} strokeWidth={2.4}/></span><div><p className="font-semibold tracking-tight">Voice Production Studio</p><p className="text-xs text-[#8ea99e]">Client demo · German training audio</p></div></div><div className="hidden items-center gap-2 rounded-full border border-[#80f0bd]/20 bg-[#80f0bd]/8 px-3 py-1.5 text-xs text-[#a6f5cf] sm:flex"><span className="h-1.5 w-1.5 rounded-full bg-[#80f0bd]"/>Secure API project</div></div></header>
    <div className="mx-auto grid max-w-[1440px] lg:grid-cols-[220px_minmax(0,1fr)]">
      <aside className="hidden min-h-[calc(100vh-73px)] border-r border-white/10 px-5 py-7 lg:block"><p className="mb-4 text-[11px] font-semibold uppercase tracking-[.16em] text-[#678277]">Workflow</p>{[["script","01","Script & translation"],["voice","02","Voice direction"],["qc","03","Quality control"]].map(([id,n,label])=>{const active=stage===id;return <button key={id} onClick={()=>setStage(id as Stage)} className={`mb-2 flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-sm transition ${active?"bg-white/10 text-white":"text-[#87a197] hover:bg-white/5"}`}><span className={`grid h-7 w-7 place-items-center rounded-lg text-xs ${active?"bg-[#80f0bd] font-bold text-[#07110e]":"border border-white/10"}`}>{n}</span>{label}</button>})}<div className="mt-9 rounded-2xl border border-white/10 bg-white/[.035] p-4"><p className="text-xs font-semibold text-[#c6dbd2]">Project output</p><div className="mt-3 flex items-center gap-3 text-sm text-[#8ea99e]"><FileAudio size={18}/>MP3 · German</div><div className="mt-2 flex items-center gap-3 text-sm text-[#8ea99e]"><ShieldCheck size={18}/>QC report</div></div></aside>
      <section className="min-w-0 px-4 py-6 sm:px-7 md:py-8"><div className="mx-auto max-w-6xl">
        <div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><p className="mb-1 text-sm font-medium text-[#80f0bd]">Clip 01 · Version 1</p><h1 className="text-2xl font-semibold tracking-tight sm:text-3xl">Data Security Introduction</h1></div><div className="flex rounded-xl border border-white/10 bg-white/[.035] p-1 text-xs">{(["script","voice","qc"] as Stage[]).map(item=><button key={item} onClick={()=>setStage(item)} className={`rounded-lg px-3 py-2 capitalize ${stage===item?"bg-white/12 text-white":"text-[#789187]"}`}>{item}</button>)}</div></div>
        {stage==="script"&&<div className="space-y-5"><div className="grid gap-4 xl:grid-cols-2"><ScriptCard label="Source script" language="English · Source of truth" value={english} onChange={setEnglish}/><ScriptCard label="Localized script" language="German · Standard (de-DE)" value={german} onChange={v=>{setGerman(v);setQc(null);setAudioUrl("")}} accent/></div><div className="flex flex-col gap-4 rounded-2xl border border-white/10 bg-white/[.035] p-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#8cb5ff]/12 text-[#a8c7ff]"><Languages size={20}/></span><div><p className="text-sm font-medium">Meaning-preserving translation</p><p className="text-xs text-[#789187]">Formal training language · technical terms protected</p></div></div><button onClick={translate} disabled={!!busy||!english.trim()} className="primary-btn">{busy==="translate"?<LoaderCircle className="animate-spin" size={17}/>:<Sparkles size={17}/>}Translate & review<ChevronRight size={16}/></button></div></div>}
        {stage==="voice"&&<div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_360px]"><div className="panel p-5 sm:p-6"><div className="mb-5 flex items-center justify-between"><div><h2 className="text-lg font-semibold">Voice direction</h2><p className="mt-1 text-sm text-[#789187]">Control how this clip should sound.</p></div><Volume2 className="text-[#80f0bd]"/></div><label className="field-label">Delivery style</label><div className="mb-6 flex flex-wrap gap-2">{directionPresets.map(item=><button key={item} onClick={()=>setTone(item)} className={`choice ${tone===item?"choice-active":""}`}>{item}</button>)}</div><div className="mb-6 grid gap-5 sm:grid-cols-2"><RangeField label="Speaking pace" left="Slower" right="Faster" value={speed} setValue={setSpeed}/><RangeField label="Energy" left="Reserved" right="Expressive" value={energy} setValue={setEnergy}/></div><label className="field-label" htmlFor="direction">Custom direction</label><textarea id="direction" value={direction} onChange={e=>setDirection(e.target.value)} className="script-area min-h-28"/></div><div className="space-y-5"><div className="panel p-5"><label className="field-label" htmlFor="voice">AI voice</label><select id="voice" value={voice} onChange={e=>setVoice(e.target.value)} className="input-control capitalize">{voiceOptions.map(v=><option key={v} value={v}>{v}</option>)}</select><div className="mt-5 rounded-xl bg-[#80f0bd]/8 p-4 text-sm text-[#b9d5c9]"><p className="font-medium text-[#a6f5cf]">German script locked</p><p className="mt-1 text-xs leading-5 text-[#789187]">{words} words · approximately {Math.max(8,Math.round(words/2.1))} seconds</p></div></div><button onClick={generate} disabled={!!busy||!german.trim()} className="primary-btn w-full justify-center py-3.5">{busy==="generate"?<LoaderCircle className="animate-spin" size={18}/>:<AudioLines size={18}/>} {busy==="generate"?"Generating & checking…":"Generate voiceover"}</button></div></div>}
        {stage==="qc"&&<div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_380px]"><div className="space-y-5"><div className="panel overflow-hidden"><div className="border-b border-white/10 p-5"><p className="text-xs font-semibold uppercase tracking-[.14em] text-[#789187]">Generated output</p><h2 className="mt-1 text-lg font-semibold">German voiceover · v1</h2></div><div className="p-5">{audioUrl?<audio className="w-full accent-[#80f0bd]" controls src={audioUrl}/>:<div className="rounded-xl border border-dashed border-white/15 p-7 text-center text-sm text-[#789187]">Generate a voiceover to hear the clip.</div>}<p className="mt-5 rounded-xl bg-white/[.035] p-4 text-sm leading-6 text-[#b8ccc4]">{german}</p><div className="mt-4 flex flex-wrap gap-2">{audioUrl&&<a href={audioUrl} download="german-training-clip-v1.mp3" className="secondary-btn"><Download size={16}/>Download MP3</a>}<button onClick={()=>setStage("voice")} className="secondary-btn"><RotateCcw size={16}/>Adjust delivery</button></div></div></div>{qc?.humanReview&&<HumanReviewCard review={qc.humanReview}/>} {qc?.transcript&&<div className="panel p-5"><p className="field-label">What the audio said</p><p className="text-sm leading-6 text-[#b8ccc4]">{qc.transcript}</p></div>}</div><div className="panel p-5"><div className="flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.14em] text-[#789187]">Automated QC</p><h2 className="mt-1 text-lg font-semibold">Content integrity</h2></div><div className={`grid h-16 w-16 place-items-center rounded-full border-4 ${qc?.status==="pass"?"border-[#80f0bd] text-[#80f0bd]":"border-[#f7c56b] text-[#f7c56b]"}`}><span className="text-lg font-bold">{qc?.score??"—"}</span></div></div><div className="mt-6 space-y-3">{(qc?.checks??defaultChecks).map(check=><div key={check.label} className="flex gap-3 rounded-xl border border-white/8 bg-white/[.025] p-3.5"><span className={`mt-0.5 grid h-5 w-5 shrink-0 place-items-center rounded-full ${check.passed?"bg-[#80f0bd] text-[#07110e]":"bg-[#f7c56b] text-[#3c2b0d]"}`}><Check size={13} strokeWidth={3}/></span><div><p className="text-sm font-medium">{check.label}</p><p className="mt-0.5 text-xs leading-5 text-[#789187]">{check.detail}</p></div></div>)}</div><div className="mt-5 rounded-xl border border-[#80f0bd]/20 bg-[#80f0bd]/8 p-4"><p className="text-sm font-semibold text-[#a6f5cf]">{qc?(qc.status==="pass"?"Ready for internal approval":"Manual review recommended"):"Waiting for generated audio"}</p><p className="mt-1 text-xs leading-5 text-[#789187]">Every regenerated version runs through QC again.</p></div></div></div>}
        {error&&<div role="alert" className="mt-5 rounded-xl border border-red-400/25 bg-red-400/10 px-4 py-3 text-sm text-red-200">{error}</div>}
      </div></section>
    </div>
  </main>
}

const defaultChecks=[{label:"Script match",detail:"German audio will be transcribed and compared.",passed:true},{label:"Numbers & terminology",detail:"Protected terms and numeric values will be checked.",passed:true},{label:"Pacing & delivery",detail:"Voice settings are recorded with this version.",passed:true}];
const SAMPLE_QC:QcResult={score:100,status:"pass",transcript:SAMPLE_GERMAN,checks:[{label:"Script match",detail:"100% agreement with the approved German script.",passed:true},{label:"Numbers & terminology",detail:"No missing, added, or changed protected content.",passed:true},{label:"Voice consistency",detail:"Selected narrator and delivery settings are recorded.",passed:true},{label:"Pacing & delivery",detail:"Moderate-slow pacing suitable for training content.",passed:true}],humanReview:{humanScore:91,verdict:"Approved with a minor suggestion",pronunciation:"Clear Standard German",tone:"Neutral and professional",pacing:"Moderate-slow and clear",audioQuality:"Clean and consistent",humanLikeness:"Natural educational delivery",summary:"This voice is a strong fit for professional security training. It sounds informative and restrained rather than promotional or dramatic.",suggestions:["Add a slightly clearer pause after ‘Zugriffs’ before ‘und zur Gewährleistung’.","Keep the current restrained energy and avoid increasing dramatic emphasis."]}};
function ScriptCard({label,language,value,onChange,accent=false}:{label:string;language:string;value:string;onChange:(v:string)=>void;accent?:boolean}){return <div className={`panel p-5 sm:p-6 ${accent?"ring-1 ring-[#80f0bd]/25":""}`}><div className="mb-4 flex items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-[.14em] text-[#789187]">{label}</p><p className="mt-1 text-sm text-[#b8ccc4]">{language}</p></div>{accent&&<span className="rounded-full bg-[#80f0bd]/10 px-2.5 py-1 text-[11px] font-semibold text-[#a6f5cf]">Editable</span>}</div><textarea aria-label={label} value={value} onChange={e=>onChange(e.target.value)} className="script-area min-h-52"/><p className="mt-3 text-right text-xs text-[#60786e]">{value.length} characters</p></div>}
function RangeField({label,left,right,value,setValue}:{label:string;left:string;right:string;value:number;setValue:(n:number)=>void}){return <div><div className="mb-3 flex justify-between"><label className="field-label mb-0">{label}</label><span className="text-xs font-semibold text-[#80f0bd]">{value}%</span></div><input aria-label={label} type="range" min="0" max="100" value={value} onChange={e=>setValue(Number(e.target.value))} className="w-full accent-[#80f0bd]"/><div className="mt-1 flex justify-between text-[11px] text-[#60786e]"><span>{left}</span><span>{right}</span></div></div>}
function HumanReviewCard({review}:{review:HumanReview}){const rows=[["Pronunciation",review.pronunciation],["Tone",review.tone],["Pacing",review.pacing],["Audio quality",review.audioQuality],["Human likeness",review.humanLikeness]];return <div className="panel overflow-hidden"><div className="flex items-center justify-between border-b border-white/10 p-5"><div><p className="text-xs font-semibold uppercase tracking-[.14em] text-[#d8a7ff]">Human Voice Review</p><h2 className="mt-1 text-lg font-semibold">{review.verdict}</h2></div><div className="rounded-xl bg-[#d8a7ff]/10 px-3 py-2 text-center"><p className="text-xl font-bold text-[#e4c1ff]">{review.humanScore}</p><p className="text-[10px] uppercase tracking-wider text-[#9e7ab8]">natural</p></div></div><div className="p-5"><p className="mb-4 text-sm leading-6 text-[#c7d9d1]">{review.summary}</p><div className="grid gap-2 sm:grid-cols-2">{rows.map(([label,value])=><div key={label} className="rounded-xl bg-white/[.035] p-3"><p className="text-[11px] font-semibold uppercase tracking-wider text-[#718b80]">{label}</p><p className="mt-1 text-sm text-[#c3d7ce]">{value}</p></div>)}</div>{review.suggestions.length>0&&<div className="mt-4 rounded-xl border border-[#d8a7ff]/15 bg-[#d8a7ff]/7 p-4"><p className="text-xs font-semibold uppercase tracking-wider text-[#d8a7ff]">Suggestions to sound more human</p><ul className="mt-2 space-y-2 text-sm leading-5 text-[#b8ccc4]">{review.suggestions.map((item,i)=><li key={i} className="flex gap-2"><span className="text-[#d8a7ff]">•</span>{item}</li>)}</ul></div>}</div></div>}
